<?php

$quote = Mage::getSingleton('checkout/session')->getQuote();

$checkoutData['currency'] = Mage::app()->getStore()->getCurrentCurrencyCode();

$totals = $quote->getTotals(); //Total object
$checkoutData['grandTotal'] = $totals["grand_total"]->getValue(); //Grandtotal value

$checkoutData['email'] = $quote->getBillingAddress()->getEmail();

$checkoutData['message'] = $this->getMethod()->getConfigData('message');


if (file_exists(MAGENTO_ROOT . '/data/currencies.json')) {
    $currency_json_data = json_decode(file_get_contents(MAGENTO_ROOT . '/data/currencies.json'), 1);
    $checkoutData['currency_multiplier'] = floatval($currency_json_data[$checkoutData['currency']]);
} else {
    $checkoutData['currency_multiplier'] = floatval(100);
}

if ( $this->getMethod()->getConfigData('test_mode') ){
    $checkoutData['key'] = $this->getMethod()->getConfigData('test_open_key');
}
else{
    $checkoutData['key'] = $this->getMethod()->getConfigData('live_open_key');
}

print "<pre>";
print_r($checkoutData);
print "</pre>";

?>
<script>

    var currency_multiplier = <?php echo "'" . $checkoutData['currency_multiplier'] . "';"; ?>
    var key = <?php echo "'" . $checkoutData['key'] . "';"; ?>
    var currency = <?php echo "'" . $checkoutData['currency'] . "';"; ?>

    if (typeof quoteBaseGrandTotal === "undefined") {
        var quoteBaseGrandTotal = <?php echo $checkoutData['grandTotal']; ?>;
    }

    var amount = quoteBaseGrandTotal * currency_multiplier; // e.g. 100 = $1.00
    var email = <?php echo "'" . $checkoutData['email'] . "';"; ?> // should be a customer email from order info

    console.log("key:" + key);
    console.log("currency_multiplier:" + currency_multiplier);
    console.log("currency:" + currency);
    console.log("amount:" + amount);
    console.log("email:" + email);

    if (StartCheckout) {
        StartCheckout.config({
            key: key,
            formLabel: 'Ok',
            tabOnMobile: true,
            complete: function (params) {
                submitFormWithToken(params); // params.token.id, params.email
            }
        });
    }

    function submitFormWithToken(params) {
        // params.token.id, params.email are passed

        // remove old values if any
        jQuery('input[name=payfortToken], input[name=payfortEmail]').remove();

        // Append the params to the form
        frmCheckout = jQuery("#p_method_gateway");
        frmCheckout.append("<input type='hidden' name='payfortToken' value='" + params.token.id + "'>");
        frmCheckout.append("<input type='hidden' name='payfortEmail' value='" + params.email + "'>");

        // Set text for entered card
        jQuery('#payfortCardDetails').show().html("<p>Pay with Card: xxxx-xxxx-xxxx-<b>" + params.token.card.last4 + "</b></p>");

        //hide button
        jQuery('#btnCheckout').hide();

        // show link to change card details
        jQuery('#changeCardBtn').show();
        payment.save();
    }

    jQuery(document).on('click', '#changeCardBtn', function (event) {
        event.preventDefault();
        openPaymentPopup();
    });

    function openPaymentPopup() {

        StartCheckout.open({
            amount: amount,
            currency: currency,
            email: email
        });

    }

    Payment.prototype.save = Payment.prototype.save.wrap(function (save) {
        var validator = new Validation(this.form);
        if (jQuery("input[type='radio'][name='payment[method]']:checked").val() == "gateway") {
            if (jQuery('input[name=payfortToken]').length != 0) {
                if (jQuery('input[name=payfortToken]').val() !== "") {
                    save();
                } else {
                    openPaymentPopup();
                }
            } else {
               openPaymentPopup(); 
            }
        } else {
            save();
        }

    });
</script>
<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div>
        <div id='payfortCardDetails'></div>
        <a id="changeCardBtn"  href="#_" style="display:none">Change Card Details</a>
    </div>
</div>
<div>
    <?php echo $checkoutData['message']; ?>
</div>
